#!/bin/bash
set -e

echo "🚀 Deploy script starting..."

# Patch schema provider based on DATABASE_URL
if [[ "$DATABASE_URL" == postgres* ]] || [[ "$DATABASE_URL" == postgresql* ]]; then
  echo "📦 PostgreSQL detected — patching schema provider..."
  sed -i 's/provider = env("DATABASE_PROVIDER")/provider = "postgresql"/' prisma/schema.prisma
  sed -i 's/provider = "sqlite"/provider = "postgresql"/' prisma/schema.prisma
  # Also update migration_lock.toml
  echo -e '# Please do not edit this file manually\n# It should be added in your version-control system (i.e. Git)\nprovider = "postgresql"' > prisma/migrations/migration_lock.toml
  echo "✅ Schema patched to postgresql"
  # Use db push for full schema sync (safe for additive changes)
  npx prisma db push --accept-data-loss
else
  echo "📦 SQLite detected — skipping schema patch"
fi

echo "✅ Database ready"
echo "🚀 Starting server..."
node dist/index.js
