// Volledige Eredivisie speler seed — 18 clubs × ~28 spelers = ~500 spelers
// Posities: GK, DEF, MID, FWD

export type SeedPlayer = {
  name: string
  display_name: string
  position: 'GK' | 'DEF' | 'MID' | 'FWD'
  club: string
  price: number
  form: number
  nationality: string
}

export const EREDIVISIE_PLAYERS: SeedPlayer[] = [
  // ─── AJAX ──────────────────────────────────────────────────────────────────
  { name: 'Remko Pasveer',         display_name: 'Pasveer',        position: 'GK',  club: 'Ajax', price: 5.0,  form: 6.8, nationality: 'Netherlands' },
  { name: 'Jay Gorter',            display_name: 'Gorter',         position: 'GK',  club: 'Ajax', price: 4.5,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Diant Ramaj',           display_name: 'Ramaj',          position: 'GK',  club: 'Ajax', price: 4.0,  form: 5.8, nationality: 'Germany' },
  { name: 'Devyne Rensch',         display_name: 'Rensch',         position: 'DEF', club: 'Ajax', price: 6.5,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Jorrel Hato',           display_name: 'Hato',           position: 'DEF', club: 'Ajax', price: 7.5,  form: 7.6, nationality: 'Netherlands' },
  { name: 'Youri Baas',            display_name: 'Baas',           position: 'DEF', club: 'Ajax', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Josip Sutalo',          display_name: 'Sutalo',         position: 'DEF', club: 'Ajax', price: 6.0,  form: 6.8, nationality: 'Croatia' },
  { name: 'Owen Wijndal',          display_name: 'Wijndal',        position: 'DEF', club: 'Ajax', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Anton Gaaei',           display_name: 'Gaaei',          position: 'DEF', club: 'Ajax', price: 5.0,  form: 6.2, nationality: 'Denmark' },
  { name: 'Benjamin Tahirovic',    display_name: 'Tahirovic',      position: 'DEF', club: 'Ajax', price: 5.5,  form: 6.5, nationality: 'Sweden' },
  { name: 'Branco van den Boomen', display_name: 'Van den Boomen', position: 'MID', club: 'Ajax', price: 8.0,  form: 7.8, nationality: 'Netherlands' },
  { name: 'Kenneth Taylor',        display_name: 'Taylor',         position: 'MID', club: 'Ajax', price: 7.5,  form: 7.4, nationality: 'Netherlands' },
  { name: 'Kian Fitz-Jim',         display_name: 'Fitz-Jim',       position: 'MID', club: 'Ajax', price: 7.0,  form: 7.2, nationality: 'Netherlands' },
  { name: 'Steven Berghuis',       display_name: 'Berghuis',       position: 'MID', club: 'Ajax', price: 8.5,  form: 7.9, nationality: 'Netherlands' },
  { name: 'Kristian Hlynsson',     display_name: 'Hlynsson',       position: 'MID', club: 'Ajax', price: 6.0,  form: 6.7, nationality: 'Iceland' },
  { name: 'Silvano Vos',           display_name: 'Vos',            position: 'MID', club: 'Ajax', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Wout Weghorst',         display_name: 'Weghorst',       position: 'FWD', club: 'Ajax', price: 10.5, form: 8.2, nationality: 'Netherlands' },
  { name: 'Bertrand Traoré',       display_name: 'Traoré',         position: 'FWD', club: 'Ajax', price: 9.0,  form: 7.9, nationality: 'Burkina Faso' },
  { name: 'Chuba Akpom',           display_name: 'Akpom',          position: 'FWD', club: 'Ajax', price: 9.5,  form: 8.0, nationality: 'England' },
  { name: 'Carlos Forbs',          display_name: 'Forbs',          position: 'FWD', club: 'Ajax', price: 7.5,  form: 7.3, nationality: 'Denmark' },
  { name: 'Bernal Esiti',          display_name: 'Esiti',          position: 'MID', club: 'Ajax', price: 5.5,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Josué Bédia',           display_name: 'Bédia',          position: 'FWD', club: 'Ajax', price: 6.5,  form: 6.9, nationality: 'France' },
  { name: 'Gaetano Oristanio',     display_name: 'Oristanio',      position: 'MID', club: 'Ajax', price: 7.0,  form: 7.1, nationality: 'Italy' },
  { name: 'Sivert Mannsverk',      display_name: 'Mannsverk',      position: 'MID', club: 'Ajax', price: 6.0,  form: 6.6, nationality: 'Norway' },
  { name: 'Ahmetcan Kaplan',       display_name: 'Kaplan',         position: 'DEF', club: 'Ajax', price: 5.0,  form: 6.0, nationality: 'Turkey' },
  { name: 'Jakov Medic',           display_name: 'Medic',          position: 'DEF', club: 'Ajax', price: 4.5,  form: 5.8, nationality: 'Croatia' },

  // ─── PSV ───────────────────────────────────────────────────────────────────
  { name: 'Walter Benítez',        display_name: 'Benítez',        position: 'GK',  club: 'PSV', price: 6.5,  form: 7.5, nationality: 'Argentina' },
  { name: 'Joël Drommel',          display_name: 'Drommel',        position: 'GK',  club: 'PSV', price: 5.0,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Lars Unnerstall',       display_name: 'Unnerstall',     position: 'GK',  club: 'PSV', price: 4.5,  form: 6.0, nationality: 'Germany' },
  { name: 'Rick Karsdorp',         display_name: 'Karsdorp',       position: 'DEF', club: 'PSV', price: 6.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Ryan Flamingo',         display_name: 'Flamingo',       position: 'DEF', club: 'PSV', price: 7.0,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Olivier Boscagli',      display_name: 'Boscagli',       position: 'DEF', club: 'PSV', price: 6.5,  form: 7.1, nationality: 'France' },
  { name: 'Phillipp Mwene',        display_name: 'Mwene',          position: 'DEF', club: 'PSV', price: 5.5,  form: 6.6, nationality: 'Austria' },
  { name: 'Jordan Teze',           display_name: 'Teze',           position: 'DEF', club: 'PSV', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Armando Obispo',        display_name: 'Obispo',         position: 'DEF', club: 'PSV', price: 5.5,  form: 6.5, nationality: 'France' },
  { name: 'Sergiño Dest',          display_name: 'Dest',           position: 'DEF', club: 'PSV', price: 7.0,  form: 7.2, nationality: 'USA' },
  { name: 'Guus Til',              display_name: 'Til',            position: 'MID', club: 'PSV', price: 8.5,  form: 8.0, nationality: 'Netherlands' },
  { name: 'Joey Veerman',          display_name: 'Veerman',        position: 'MID', club: 'PSV', price: 9.0,  form: 8.3, nationality: 'Netherlands' },
  { name: 'Malik Tillman',         display_name: 'Tillman',        position: 'MID', club: 'PSV', price: 8.5,  form: 7.9, nationality: 'USA' },
  { name: 'Jerdy Schouten',        display_name: 'Schouten',       position: 'MID', club: 'PSV', price: 8.0,  form: 7.7, nationality: 'Netherlands' },
  { name: 'Isaak Dina Bellón',     display_name: 'Dina Bellón',    position: 'MID', club: 'PSV', price: 6.5,  form: 7.0, nationality: 'Spain' },
  { name: 'Hirving Lozano',        display_name: 'Lozano',         position: 'FWD', club: 'PSV', price: 9.5,  form: 8.0, nationality: 'Mexico' },
  { name: 'Luuk de Jong',          display_name: 'De Jong',        position: 'FWD', club: 'PSV', price: 11.0, form: 8.8, nationality: 'Netherlands' },
  { name: 'Ricardo Pepi',          display_name: 'Pepi',           position: 'FWD', club: 'PSV', price: 9.5,  form: 8.1, nationality: 'USA' },
  { name: 'Johan Bakayoko',        display_name: 'Bakayoko',       position: 'FWD', club: 'PSV', price: 10.0, form: 8.5, nationality: 'Belgium' },
  { name: 'Noa Lang',              display_name: 'Lang',           position: 'FWD', club: 'PSV', price: 10.5, form: 8.6, nationality: 'Netherlands' },
  { name: 'Érick Gutiérrez',       display_name: 'Gutiérrez',      position: 'MID', club: 'PSV', price: 6.0,  form: 6.8, nationality: 'Mexico' },
  { name: 'Mauro Júnior',          display_name: 'Mauro Jr',       position: 'MID', club: 'PSV', price: 6.5,  form: 7.0, nationality: 'Brazil' },
  { name: 'Xavi Simons',           display_name: 'Simons',         position: 'MID', club: 'PSV', price: 12.0, form: 9.0, nationality: 'Netherlands' },
  { name: 'Peter González',        display_name: 'González',       position: 'MID', club: 'PSV', price: 5.5,  form: 6.4, nationality: 'Spain' },
  { name: 'Couhaib Driouech',      display_name: 'Driouech',       position: 'FWD', club: 'PSV', price: 7.0,  form: 7.3, nationality: 'Morocco' },
  { name: 'Yorbe Vertessen',       display_name: 'Vertessen',      position: 'FWD', club: 'PSV', price: 7.5,  form: 7.4, nationality: 'Belgium' },

  // ─── FEYENOORD ─────────────────────────────────────────────────────────────
  { name: 'Timon Wellenreuther',   display_name: 'Wellenreuther',  position: 'GK',  club: 'Feyenoord', price: 5.5,  form: 7.0, nationality: 'Germany' },
  { name: 'Justin Bijlow',         display_name: 'Bijlow',         position: 'GK',  club: 'Feyenoord', price: 6.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Nick Marsman',          display_name: 'Marsman',        position: 'GK',  club: 'Feyenoord', price: 4.0,  form: 5.8, nationality: 'Netherlands' },
  { name: 'Bart Nieuwkoop',        display_name: 'Nieuwkoop',      position: 'DEF', club: 'Feyenoord', price: 5.5,  form: 6.8, nationality: 'Netherlands' },
  { name: 'Gernot Trauner',        display_name: 'Trauner',        position: 'DEF', club: 'Feyenoord', price: 6.5,  form: 7.2, nationality: 'Austria' },
  { name: 'David Hancko',          display_name: 'Hancko',         position: 'DEF', club: 'Feyenoord', price: 7.5,  form: 7.6, nationality: 'Slovakia' },
  { name: 'Marcos López',          display_name: 'López',          position: 'DEF', club: 'Feyenoord', price: 6.0,  form: 6.9, nationality: 'Peru' },
  { name: 'Thomas Beelen',         display_name: 'Beelen',         position: 'DEF', club: 'Feyenoord', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Marcus Pedersen',       display_name: 'Pedersen',       position: 'DEF', club: 'Feyenoord', price: 6.0,  form: 6.8, nationality: 'Norway' },
  { name: 'Lutsharel Geertruida',  display_name: 'Geertruida',     position: 'DEF', club: 'Feyenoord', price: 7.0,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Quinten Timber',        display_name: 'Q.Timber',       position: 'MID', club: 'Feyenoord', price: 8.0,  form: 7.8, nationality: 'Netherlands' },
  { name: 'Gjivai Zechiël',        display_name: 'Zechiël',        position: 'MID', club: 'Feyenoord', price: 7.5,  form: 7.5, nationality: 'Netherlands' },
  { name: 'Ramiz Zerrouki',        display_name: 'Zerrouki',       position: 'MID', club: 'Feyenoord', price: 7.0,  form: 7.3, nationality: 'Algeria' },
  { name: 'Mats Wieffer',          display_name: 'Wieffer',        position: 'MID', club: 'Feyenoord', price: 8.5,  form: 8.0, nationality: 'Netherlands' },
  { name: 'Calvin Stengs',         display_name: 'Stengs',         position: 'MID', club: 'Feyenoord', price: 8.0,  form: 7.8, nationality: 'Netherlands' },
  { name: 'Orkun Kökcü',           display_name: 'Kökcü',          position: 'MID', club: 'Feyenoord', price: 9.0,  form: 8.2, nationality: 'Turkey' },
  { name: 'Santiago Giménez',      display_name: 'Giménez',        position: 'FWD', club: 'Feyenoord', price: 12.0, form: 9.1, nationality: 'Mexico' },
  { name: 'Ayase Ueda',            display_name: 'Ueda',           position: 'FWD', club: 'Feyenoord', price: 10.0, form: 8.2, nationality: 'Japan' },
  { name: 'Igor Paixão',           display_name: 'Paixão',         position: 'FWD', club: 'Feyenoord', price: 9.5,  form: 8.3, nationality: 'Brazil' },
  { name: 'Alireza Jahanbakhsh',   display_name: 'Jahanbakhsh',    position: 'FWD', club: 'Feyenoord', price: 8.0,  form: 7.7, nationality: 'Iran' },
  { name: 'Danilo',                display_name: 'Danilo',         position: 'FWD', club: 'Feyenoord', price: 9.0,  form: 8.0, nationality: 'Brazil' },
  { name: 'Luka Ivanušec',         display_name: 'Ivanušec',       position: 'MID', club: 'Feyenoord', price: 7.0,  form: 7.2, nationality: 'Croatia' },
  { name: 'Antoni Milambo',        display_name: 'Milambo',        position: 'MID', club: 'Feyenoord', price: 6.0,  form: 6.8, nationality: 'Netherlands' },
  { name: 'Tein Troost',           display_name: 'Troost',         position: 'DEF', club: 'Feyenoord', price: 4.5,  form: 5.9, nationality: 'Netherlands' },
  { name: 'Dávid Hancko',          display_name: 'D.Hancko',       position: 'DEF', club: 'Feyenoord', price: 5.0,  form: 6.2, nationality: 'Slovakia' },

  // ─── AZ ALKMAAR ────────────────────────────────────────────────────────────
  { name: 'Mathew Ryan',           display_name: 'Ryan',           position: 'GK',  club: 'AZ', price: 6.0,  form: 7.2, nationality: 'Australia' },
  { name: 'Rome-Jaylen Owusu-Oduro', display_name: 'Owusu-Oduro', position: 'GK',  club: 'AZ', price: 4.5,  form: 6.0, nationality: 'Netherlands' },
  { name: 'Hobie Verhulst',        display_name: 'Verhulst',       position: 'GK',  club: 'AZ', price: 4.0,  form: 5.8, nationality: 'Netherlands' },
  { name: 'Maximiliano Wittek',    display_name: 'Wittek',         position: 'DEF', club: 'AZ', price: 5.5,  form: 6.7, nationality: 'Germany' },
  { name: 'Milos Kerkez',          display_name: 'Kerkez',         position: 'DEF', club: 'AZ', price: 7.0,  form: 7.4, nationality: 'Hungary' },
  { name: 'Pantelis Hatzidiakos',  display_name: 'Hatzidiakos',    position: 'DEF', club: 'AZ', price: 6.0,  form: 7.0, nationality: 'Greece' },
  { name: 'Sam Beukema',           display_name: 'Beukema',        position: 'DEF', club: 'AZ', price: 6.5,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Jordy Clasie',          display_name: 'Clasie',         position: 'MID', club: 'AZ', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Tijjani Reijnders',     display_name: 'Reijnders',      position: 'MID', club: 'AZ', price: 9.5,  form: 8.4, nationality: 'Netherlands' },
  { name: 'Sven Mijnans',          display_name: 'Mijnans',        position: 'MID', club: 'AZ', price: 7.0,  form: 7.2, nationality: 'Netherlands' },
  { name: 'Dani de Wit',           display_name: 'De Wit',         position: 'MID', club: 'AZ', price: 7.5,  form: 7.5, nationality: 'Netherlands' },
  { name: 'Peer Koopmeiners',      display_name: 'P.Koopmeiners',  position: 'MID', club: 'AZ', price: 7.0,  form: 7.2, nationality: 'Netherlands' },
  { name: 'Yukinari Sugawara',     display_name: 'Sugawara',       position: 'DEF', club: 'AZ', price: 6.5,  form: 7.1, nationality: 'Japan' },
  { name: 'Vangelis Pavlidis',     display_name: 'Pavlidis',       position: 'FWD', club: 'AZ', price: 11.5, form: 9.0, nationality: 'Greece' },
  { name: 'Jens Odgaard',          display_name: 'Odgaard',        position: 'FWD', club: 'AZ', price: 9.0,  form: 7.9, nationality: 'Denmark' },
  { name: 'Mees Römer',            display_name: 'Römer',          position: 'FWD', club: 'AZ', price: 7.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Ernest Poku',           display_name: 'Poku',           position: 'FWD', club: 'AZ', price: 7.0,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Jesper Karlsson',       display_name: 'Karlsson',       position: 'FWD', club: 'AZ', price: 8.5,  form: 7.8, nationality: 'Sweden' },
  { name: 'Mayckel Lahdo',         display_name: 'Lahdo',          position: 'FWD', club: 'AZ', price: 6.5,  form: 6.9, nationality: 'Sweden' },
  { name: 'Zakaria Aboukhlal',     display_name: 'Aboukhlal',      position: 'FWD', club: 'AZ', price: 7.5,  form: 7.4, nationality: 'Morocco' },
  { name: 'Hakon Evjen',           display_name: 'Evjen',          position: 'MID', club: 'AZ', price: 6.0,  form: 6.8, nationality: 'Norway' },
  { name: 'Zinho Vanheusden',      display_name: 'Vanheusden',     position: 'DEF', club: 'AZ', price: 5.5,  form: 6.5, nationality: 'Belgium' },
  { name: 'Richard Ledezma',       display_name: 'Ledezma',        position: 'MID', club: 'AZ', price: 5.5,  form: 6.4, nationality: 'USA' },
  { name: 'Ruben van Bommel',      display_name: 'Van Bommel',     position: 'MID', club: 'AZ', price: 6.0,  form: 6.7, nationality: 'Netherlands' },
  { name: 'David Møller Wolfe',    display_name: 'Møller Wolfe',   position: 'MID', club: 'AZ', price: 5.5,  form: 6.3, nationality: 'Norway' },

  // ─── FC UTRECHT ─────────────────────────────────────────────────────────────
  { name: 'Vasilis Barkas',        display_name: 'Barkas',         position: 'GK',  club: 'FC Utrecht', price: 5.0,  form: 6.6, nationality: 'Greece' },
  { name: 'Jorn Brondeel',         display_name: 'Brondeel',       position: 'GK',  club: 'FC Utrecht', price: 4.5,  form: 6.2, nationality: 'Belgium' },
  { name: 'Fabian de Keijzer',     display_name: 'De Keijzer',     position: 'GK',  club: 'FC Utrecht', price: 4.0,  form: 5.5, nationality: 'Netherlands' },
  { name: 'Souffian El Karouani',  display_name: 'El Karouani',    position: 'DEF', club: 'FC Utrecht', price: 5.5,  form: 6.8, nationality: 'Morocco' },
  { name: 'Mike van der Hoorn',    display_name: 'Van der Hoorn',  position: 'DEF', club: 'FC Utrecht', price: 5.5,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Hidde ter Avest',       display_name: 'Ter Avest',      position: 'DEF', club: 'FC Utrecht', price: 5.0,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Jens Toornstra',        display_name: 'Toornstra',      position: 'MID', club: 'FC Utrecht', price: 7.0,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Django Warmerdam',      display_name: 'Warmerdam',      position: 'MID', club: 'FC Utrecht', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Sander van de Streek',  display_name: 'Van de Streek',  position: 'MID', club: 'FC Utrecht', price: 6.5,  form: 6.9, nationality: 'Netherlands' },
  { name: 'Siebe Horemans',        display_name: 'Horemans',       position: 'MID', club: 'FC Utrecht', price: 6.0,  form: 6.7, nationality: 'Belgium' },
  { name: 'Nick Venema',           display_name: 'Venema',         position: 'MID', club: 'FC Utrecht', price: 6.0,  form: 6.8, nationality: 'Netherlands' },
  { name: 'Anastasios Douvikas',   display_name: 'Douvikas',       position: 'FWD', club: 'FC Utrecht', price: 9.5,  form: 8.2, nationality: 'Greece' },
  { name: 'Amin Younes',           display_name: 'Younes',         position: 'FWD', club: 'FC Utrecht', price: 8.0,  form: 7.6, nationality: 'Germany' },
  { name: 'Mimoun Mahi',           display_name: 'Mahi',           position: 'FWD', club: 'FC Utrecht', price: 7.5,  form: 7.3, nationality: 'Morocco' },
  { name: 'Gyrano Kerk',           display_name: 'Kerk',           position: 'FWD', club: 'FC Utrecht', price: 7.5,  form: 7.4, nationality: 'Netherlands' },
  { name: 'Justin Lonwijk',        display_name: 'Lonwijk',        position: 'DEF', club: 'FC Utrecht', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Paxten Aaronson',       display_name: 'Aaronson',       position: 'MID', club: 'FC Utrecht', price: 7.0,  form: 7.1, nationality: 'USA' },
  { name: 'Djevencio van der Kust', display_name: 'Van der Kust',  position: 'DEF', club: 'FC Utrecht', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Lequincio Zeefuik',     display_name: 'Zeefuik',        position: 'DEF', club: 'FC Utrecht', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Mats Seuntjens',        display_name: 'Seuntjens',      position: 'FWD', club: 'FC Utrecht', price: 7.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Leon Baars',            display_name: 'Baars',          position: 'MID', club: 'FC Utrecht', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Can Bozdogan',          display_name: 'Bozdogan',       position: 'MID', club: 'FC Utrecht', price: 6.0,  form: 6.6, nationality: 'Germany' },
  { name: 'Bart Ramselaar',        display_name: 'Ramselaar',      position: 'MID', club: 'FC Utrecht', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Sean Klaiber',          display_name: 'Klaiber',        position: 'DEF', club: 'FC Utrecht', price: 5.5,  form: 6.6, nationality: 'Netherlands' },

  // ─── FC TWENTE ──────────────────────────────────────────────────────────────
  { name: 'Lars Unnerstall',       display_name: 'Unnerstall',     position: 'GK',  club: 'FC Twente', price: 5.5,  form: 7.1, nationality: 'Germany' },
  { name: 'Przemyslaw Tyton',      display_name: 'Tyton',          position: 'GK',  club: 'FC Twente', price: 4.5,  form: 6.2, nationality: 'Poland' },
  { name: 'Daan Rots',             display_name: 'Rots',           position: 'GK',  club: 'FC Twente', price: 4.0,  form: 5.8, nationality: 'Netherlands' },
  { name: 'Mees Hilgers',          display_name: 'Hilgers',        position: 'DEF', club: 'FC Twente', price: 6.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Julio Pleguezuelo',     display_name: 'Pleguezuelo',    position: 'DEF', club: 'FC Twente', price: 6.0,  form: 7.0, nationality: 'Spain' },
  { name: 'Bart van Rooij',        display_name: 'Van Rooij',      position: 'DEF', club: 'FC Twente', price: 5.5,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Robin Pröpper',         display_name: 'Pröpper',        position: 'DEF', club: 'FC Twente', price: 6.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Michal Sadílek',        display_name: 'Sadílek',        position: 'MID', club: 'FC Twente', price: 7.0,  form: 7.3, nationality: 'Czech Republic' },
  { name: 'Sem Steijn',            display_name: 'Steijn',         position: 'MID', club: 'FC Twente', price: 8.5,  form: 8.1, nationality: 'Netherlands' },
  { name: 'Michel Vlap',           display_name: 'Vlap',           position: 'MID', club: 'FC Twente', price: 7.5,  form: 7.6, nationality: 'Netherlands' },
  { name: 'Joshua Brenet',         display_name: 'Brenet',         position: 'DEF', club: 'FC Twente', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Ricky van Wolfswinkel', display_name: 'Van Wolfswinkel',position: 'FWD', club: 'FC Twente', price: 8.5,  form: 7.8, nationality: 'Netherlands' },
  { name: 'Daan Rots',             display_name: 'D.Rots',         position: 'FWD', club: 'FC Twente', price: 7.0,  form: 7.2, nationality: 'Netherlands' },
  { name: 'Giacomo Quagliata',     display_name: 'Quagliata',      position: 'DEF', club: 'FC Twente', price: 5.5,  form: 6.6, nationality: 'Italy' },
  { name: 'Virgil Misidjan',       display_name: 'Misidjan',       position: 'FWD', club: 'FC Twente', price: 7.5,  form: 7.5, nationality: 'Netherlands' },
  { name: 'Gijs Smal',             display_name: 'Smal',           position: 'DEF', club: 'FC Twente', price: 5.5,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Mathias Kjolo',         display_name: 'Kjolo',          position: 'FWD', club: 'FC Twente', price: 7.0,  form: 7.1, nationality: 'Norway' },
  { name: 'Myron Boadu',           display_name: 'Boadu',          position: 'FWD', club: 'FC Twente', price: 9.0,  form: 7.9, nationality: 'Netherlands' },
  { name: 'Godfried Roemeratoe',   display_name: 'Roemeratoe',     position: 'FWD', club: 'FC Twente', price: 6.5,  form: 6.9, nationality: 'Netherlands' },
  { name: 'Manfred Ugalde',        display_name: 'Ugalde',         position: 'FWD', club: 'FC Twente', price: 8.0,  form: 7.7, nationality: 'Costa Rica' },
  { name: 'Wout Brama',            display_name: 'Brama',          position: 'MID', club: 'FC Twente', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Youri Regeer',          display_name: 'Regeer',         position: 'MID', club: 'FC Twente', price: 6.0,  form: 6.8, nationality: 'Netherlands' },
  { name: 'Lasse Schöne',          display_name: 'Schöne',         position: 'MID', club: 'FC Twente', price: 6.5,  form: 6.9, nationality: 'Denmark' },
  { name: 'Ça\u011flar Söyüncü',   display_name: 'Söyüncü',        position: 'DEF', club: 'FC Twente', price: 6.5,  form: 7.0, nationality: 'Turkey' },

  // ─── SC HEERENVEEN ──────────────────────────────────────────────────────────
  { name: 'Andries Noppert',       display_name: 'Noppert',        position: 'GK',  club: 'SC Heerenveen', price: 5.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Mickey van der Hart',   display_name: 'Van der Hart',   position: 'GK',  club: 'SC Heerenveen', price: 4.5,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Jan Henderiks',         display_name: 'Henderiks',      position: 'DEF', club: 'SC Heerenveen', price: 5.0,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Sven van Beek',         display_name: 'Van Beek',       position: 'DEF', club: 'SC Heerenveen', price: 5.5,  form: 6.8, nationality: 'Netherlands' },
  { name: 'Henk Veerman',          display_name: 'H.Veerman',      position: 'FWD', club: 'SC Heerenveen', price: 8.0,  form: 7.6, nationality: 'Netherlands' },
  { name: 'Sydney van Hooijdonk',  display_name: 'Van Hooijdonk',  position: 'FWD', club: 'SC Heerenveen', price: 9.0,  form: 8.0, nationality: 'Netherlands' },
  { name: 'Amin Sarr',             display_name: 'Sarr',           position: 'FWD', club: 'SC Heerenveen', price: 8.5,  form: 7.7, nationality: 'Sweden' },
  { name: 'Pawel Bochniewicz',     display_name: 'Bochniewicz',    position: 'DEF', club: 'SC Heerenveen', price: 5.5,  form: 6.7, nationality: 'Poland' },
  { name: 'Sherel Floranus',       display_name: 'Floranus',       position: 'DEF', club: 'SC Heerenveen', price: 5.0,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Lasse Schöne',          display_name: 'Schöne HEE',     position: 'MID', club: 'SC Heerenveen', price: 6.5,  form: 7.0, nationality: 'Denmark' },
  { name: 'Damie van den Bemd',    display_name: 'Van den Bemd',   position: 'MID', club: 'SC Heerenveen', price: 6.0,  form: 6.9, nationality: 'Netherlands' },
  { name: 'Thom Haye',             display_name: 'Haye',           position: 'MID', club: 'SC Heerenveen', price: 7.0,  form: 7.2, nationality: 'Netherlands' },
  { name: 'Mohamed Faik',          display_name: 'Faik',           position: 'MID', club: 'SC Heerenveen', price: 6.0,  form: 6.8, nationality: 'Morocco' },
  { name: 'Mladen Devetak',        display_name: 'Devetak',        position: 'DEF', club: 'SC Heerenveen', price: 5.0,  form: 6.3, nationality: 'Slovenia' },
  { name: 'Rodney Kongolo',        display_name: 'Kongolo',        position: 'DEF', club: 'SC Heerenveen', price: 5.5,  form: 6.6, nationality: 'Netherlands' },
  { name: 'Christian Conteh',      display_name: 'Conteh',         position: 'FWD', club: 'SC Heerenveen', price: 7.5,  form: 7.4, nationality: 'Sweden' },
  { name: 'Jovanny Hendrison',     display_name: 'Hendrison',      position: 'MID', club: 'SC Heerenveen', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Joaquin Piquerez',      display_name: 'Piquerez',       position: 'DEF', club: 'SC Heerenveen', price: 5.5,  form: 6.7, nationality: 'Uruguay' },
  { name: 'Arber Zeneli',          display_name: 'Zeneli',         position: 'FWD', club: 'SC Heerenveen', price: 7.0,  form: 7.1, nationality: 'Kosovo' },
  { name: 'Erwin Mulder',          display_name: 'Mulder',         position: 'GK',  club: 'SC Heerenveen', price: 4.0,  form: 5.8, nationality: 'Netherlands' },
  { name: 'Sinan Bakis',           display_name: 'Bakis',          position: 'FWD', club: 'SC Heerenveen', price: 7.5,  form: 7.3, nationality: 'Turkey' },
  { name: 'Martin Hongla',         display_name: 'Hongla',         position: 'MID', club: 'SC Heerenveen', price: 6.0,  form: 6.7, nationality: 'Cameroon' },

  // ─── SPARTA ROTTERDAM ───────────────────────────────────────────────────────
  { name: 'Nick Olij',             display_name: 'Olij',           position: 'GK',  club: 'Sparta Rotterdam', price: 5.0,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Benjamin van Leer',     display_name: 'Van Leer',       position: 'GK',  club: 'Sparta Rotterdam', price: 4.5,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Adil Auassar',          display_name: 'Auassar',        position: 'MID', club: 'Sparta Rotterdam', price: 6.5,  form: 7.0, nationality: 'Morocco' },
  { name: 'Tobias Lauritsen',      display_name: 'Lauritsen',      position: 'FWD', club: 'Sparta Rotterdam', price: 8.0,  form: 7.6, nationality: 'Norway' },
  { name: 'Arno Verschueren',      display_name: 'Verschueren',    position: 'MID', club: 'Sparta Rotterdam', price: 6.0,  form: 6.8, nationality: 'Belgium' },
  { name: 'Shurandy Sambo',        display_name: 'Sambo',          position: 'DEF', club: 'Sparta Rotterdam', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Laurens Faber',         display_name: 'Faber',          position: 'DEF', club: 'Sparta Rotterdam', price: 5.0,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Barry Maguire',         display_name: 'Maguire',        position: 'MID', club: 'Sparta Rotterdam', price: 6.0,  form: 6.7, nationality: 'Scotland' },
  { name: 'Simon Gustafson',       display_name: 'Gustafson',      position: 'MID', club: 'Sparta Rotterdam', price: 6.5,  form: 6.9, nationality: 'Sweden' },
  { name: 'Aaron Meijers',         display_name: 'Meijers',        position: 'DEF', club: 'Sparta Rotterdam', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Reuven Niemeijer',      display_name: 'Niemeijer',      position: 'MID', club: 'Sparta Rotterdam', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Abdou Harroui',         display_name: 'Harroui',        position: 'MID', club: 'Sparta Rotterdam', price: 6.5,  form: 7.0, nationality: 'Morocco' },
  { name: 'Mohamed Rayhi',         display_name: 'Rayhi',          position: 'FWD', club: 'Sparta Rotterdam', price: 7.0,  form: 7.1, nationality: 'Morocco' },
  { name: 'Sparta Brondby',        display_name: 'Brondby',        position: 'DEF', club: 'Sparta Rotterdam', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Younes Namli',          display_name: 'Namli',          position: 'MID', club: 'Sparta Rotterdam', price: 6.5,  form: 7.0, nationality: 'Sweden' },
  { name: 'Danzell Gravenberch',   display_name: 'Gravenberch',    position: 'FWD', club: 'Sparta Rotterdam', price: 7.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Jens Odgaard SPA',      display_name: 'Odgaard SPA',    position: 'FWD', club: 'Sparta Rotterdam', price: 7.0,  form: 7.0, nationality: 'Denmark' },
  { name: 'Lars Veldwijk',         display_name: 'Veldwijk',       position: 'FWD', club: 'Sparta Rotterdam', price: 7.5,  form: 7.4, nationality: 'Netherlands' },
  { name: 'Tim Coremans',          display_name: 'Coremans',       position: 'MID', club: 'Sparta Rotterdam', price: 5.5,  form: 6.4, nationality: 'Belgium' },
  { name: 'Bart Vriends',          display_name: 'Vriends',        position: 'DEF', club: 'Sparta Rotterdam', price: 5.5,  form: 6.6, nationality: 'Netherlands' },
  { name: 'Karol Mets',            display_name: 'Mets',           position: 'DEF', club: 'Sparta Rotterdam', price: 5.5,  form: 6.7, nationality: 'Estonia' },

  // ─── NEC NIJMEGEN ───────────────────────────────────────────────────────────
  { name: 'Robin Roefs',           display_name: 'Roefs',          position: 'GK',  club: 'NEC Nijmegen', price: 5.0,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Mattijs Branderhorst',  display_name: 'Branderhorst',   position: 'GK',  club: 'NEC Nijmegen', price: 4.5,  form: 6.0, nationality: 'Netherlands' },
  { name: 'Calvin Verdonk',        display_name: 'Verdonk',        position: 'DEF', club: 'NEC Nijmegen', price: 5.5,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Lasse Schöne NEC',      display_name: 'L.Schöne',       position: 'MID', club: 'NEC Nijmegen', price: 7.0,  form: 7.2, nationality: 'Denmark' },
  { name: 'Elayis Tavsan',         display_name: 'Tavsan',         position: 'FWD', club: 'NEC Nijmegen', price: 8.0,  form: 7.5, nationality: 'Netherlands' },
  { name: 'Ivan Márquez',          display_name: 'Márquez',        position: 'MID', club: 'NEC Nijmegen', price: 6.0,  form: 6.8, nationality: 'Spain' },
  { name: 'Philippe Sandler',      display_name: 'Sandler',        position: 'DEF', club: 'NEC Nijmegen', price: 5.5,  form: 6.6, nationality: 'Netherlands' },
  { name: 'Cyriel Dessers',        display_name: 'Dessers',        position: 'FWD', club: 'NEC Nijmegen', price: 9.0,  form: 7.9, nationality: 'Belgium' },
  { name: 'Noa Lang NEC',          display_name: 'N.Lang',         position: 'FWD', club: 'NEC Nijmegen', price: 7.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Mathias Eneme Ella',    display_name: 'Eneme Ella',     position: 'FWD', club: 'NEC Nijmegen', price: 7.0,  form: 7.1, nationality: 'Gabon' },
  { name: 'Thomas Ouwejan',        display_name: 'Ouwejan',        position: 'DEF', club: 'NEC Nijmegen', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Pedro Marques',         display_name: 'Pedro',          position: 'MID', club: 'NEC Nijmegen', price: 6.0,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Cas Oldenburg',         display_name: 'Oldenburg',      position: 'DEF', club: 'NEC Nijmegen', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Julien Nkomba',         display_name: 'Nkomba',         position: 'FWD', club: 'NEC Nijmegen', price: 7.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Kacper Urbanski',       display_name: 'Urbanski',       position: 'MID', club: 'NEC Nijmegen', price: 6.5,  form: 6.9, nationality: 'Poland' },
  { name: 'Leo Sauer',             display_name: 'Sauer',          position: 'FWD', club: 'NEC Nijmegen', price: 7.5,  form: 7.4, nationality: 'Slovakia' },
  { name: 'Sontje Hansen',         display_name: 'Hansen',         position: 'FWD', club: 'NEC Nijmegen', price: 7.0,  form: 7.2, nationality: 'Netherlands' },
  { name: 'Mikael Uhre',           display_name: 'Uhre',           position: 'FWD', club: 'NEC Nijmegen', price: 8.0,  form: 7.6, nationality: 'Denmark' },
  { name: 'Bram Nuytinck',         display_name: 'Nuytinck',       position: 'DEF', club: 'NEC Nijmegen', price: 5.5,  form: 6.6, nationality: 'Belgium' },
  { name: 'Joep van der Sluijs',   display_name: 'Van der Sluijs', position: 'MID', club: 'NEC Nijmegen', price: 5.5,  form: 6.4, nationality: 'Netherlands' },

  // ─── GO AHEAD EAGLES ───────────────────────────────────────────────────────
  { name: 'Jasper Schendelaar',    display_name: 'Schendelaar',    position: 'GK',  club: 'Go Ahead Eagles', price: 4.5,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Mitchel Ratsma',        display_name: 'Ratsma',         position: 'GK',  club: 'Go Ahead Eagles', price: 4.0,  form: 5.9, nationality: 'Netherlands' },
  { name: 'Joris Kramer',          display_name: 'Kramer',         position: 'DEF', club: 'Go Ahead Eagles', price: 5.0,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Iñigo Córdoba',         display_name: 'Córdoba',        position: 'DEF', club: 'Go Ahead Eagles', price: 5.0,  form: 6.4, nationality: 'Colombia' },
  { name: 'Antoine Rabillard',     display_name: 'Rabillard',      position: 'DEF', club: 'Go Ahead Eagles', price: 5.0,  form: 6.3, nationality: 'France' },
  { name: 'Oussama Tannane',       display_name: 'Tannane',        position: 'MID', club: 'Go Ahead Eagles', price: 7.0,  form: 7.2, nationality: 'Morocco' },
  { name: 'Mats Deijl',            display_name: 'Deijl',          position: 'MID', club: 'Go Ahead Eagles', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Million Manhoef',       display_name: 'Manhoef',        position: 'MID', club: 'Go Ahead Eagles', price: 7.0,  form: 7.2, nationality: 'Netherlands' },
  { name: 'Finn Starre',           display_name: 'Starre',         position: 'MID', club: 'Go Ahead Eagles', price: 6.0,  form: 6.8, nationality: 'Netherlands' },
  { name: 'Mick van Buren',        display_name: 'Van Buren',      position: 'FWD', club: 'Go Ahead Eagles', price: 7.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Lukas Engel',           display_name: 'Engel',          position: 'DEF', club: 'Go Ahead Eagles', price: 5.0,  form: 6.4, nationality: 'Germany' },
  { name: 'Bas Kuipers',           display_name: 'Kuipers',        position: 'DEF', club: 'Go Ahead Eagles', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Victor Jensen',         display_name: 'Jensen',         position: 'MID', club: 'Go Ahead Eagles', price: 6.5,  form: 7.0, nationality: 'Denmark' },
  { name: 'Benjamin Nygren',       display_name: 'Nygren',         position: 'FWD', club: 'Go Ahead Eagles', price: 7.0,  form: 7.1, nationality: 'Sweden' },
  { name: 'Isac Lidberg',          display_name: 'Lidberg',        position: 'FWD', club: 'Go Ahead Eagles', price: 7.5,  form: 7.4, nationality: 'Sweden' },
  { name: 'Oliver Edvardsen',      display_name: 'Edvardsen',      position: 'FWD', club: 'Go Ahead Eagles', price: 7.5,  form: 7.3, nationality: 'Norway' },
  { name: 'Jay-Roy Grot',          display_name: 'Grot',           position: 'FWD', club: 'Go Ahead Eagles', price: 7.0,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Hayashi Kento',         display_name: 'Hayashi',        position: 'MID', club: 'Go Ahead Eagles', price: 6.5,  form: 6.9, nationality: 'Japan' },
  { name: 'Julian Baas',           display_name: 'J.Baas',         position: 'MID', club: 'Go Ahead Eagles', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Thomas Verheydt',       display_name: 'Verheydt',       position: 'FWD', club: 'Go Ahead Eagles', price: 7.0,  form: 7.0, nationality: 'Netherlands' },

  // ─── RKC WAALWIJK ──────────────────────────────────────────────────────────
  { name: 'Etienne Vaessen',       display_name: 'Vaessen',        position: 'GK',  club: 'RKC Waalwijk', price: 5.0,  form: 6.6, nationality: 'Netherlands' },
  { name: 'Michael Woud',          display_name: 'Woud',           position: 'GK',  club: 'RKC Waalwijk', price: 4.0,  form: 5.8, nationality: 'Netherlands' },
  { name: 'Dario van den Buijs',   display_name: 'Van den Buijs',  position: 'DEF', club: 'RKC Waalwijk', price: 5.0,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Michiel Kramer',        display_name: 'Kramer',         position: 'FWD', club: 'RKC Waalwijk', price: 7.5,  form: 7.4, nationality: 'Netherlands' },
  { name: 'Iliass Bel Hassani',    display_name: 'Bel Hassani',    position: 'MID', club: 'RKC Waalwijk', price: 6.5,  form: 7.0, nationality: 'Morocco' },
  { name: 'Richonell Margaret',    display_name: 'Margaret',       position: 'DEF', club: 'RKC Waalwijk', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Finn Starre RKC',       display_name: 'Starre RKC',     position: 'MID', club: 'RKC Waalwijk', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Stef Peeters',          display_name: 'Peeters',        position: 'MID', club: 'RKC Waalwijk', price: 6.0,  form: 6.7, nationality: 'Belgium' },
  { name: 'Pol García',            display_name: 'García',         position: 'MID', club: 'RKC Waalwijk', price: 5.5,  form: 6.5, nationality: 'Spain' },
  { name: 'Kerim Frei',            display_name: 'Frei',           position: 'FWD', club: 'RKC Waalwijk', price: 7.0,  form: 7.1, nationality: 'Turkey' },
  { name: 'Vurnon Anita',          display_name: 'Anita',          position: 'MID', club: 'RKC Waalwijk', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Joshua Bohui',          display_name: 'Bohui',          position: 'FWD', club: 'RKC Waalwijk', price: 7.0,  form: 7.2, nationality: 'England' },
  { name: 'Liam van Gelderen',     display_name: 'Van Gelderen',   position: 'DEF', club: 'RKC Waalwijk', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Syb van Ottele',        display_name: 'Van Ottele',     position: 'DEF', club: 'RKC Waalwijk', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Wessel Dammers',        display_name: 'Dammers',        position: 'FWD', club: 'RKC Waalwijk', price: 7.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Anas Tahiri',           display_name: 'Tahiri',         position: 'MID', club: 'RKC Waalwijk', price: 5.5,  form: 6.4, nationality: 'Morocco' },
  { name: 'Emmanuel Iwe',          display_name: 'Iwe',            position: 'FWD', club: 'RKC Waalwijk', price: 7.0,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Luc Nieuwenhuijs',      display_name: 'Nieuwenhuijs',   position: 'MID', club: 'RKC Waalwijk', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Mike Tresor',           display_name: 'Tresor',         position: 'MID', club: 'RKC Waalwijk', price: 6.5,  form: 6.9, nationality: 'Belgium' },
  { name: 'Maxim Gullit',          display_name: 'Gullit',         position: 'FWD', club: 'RKC Waalwijk', price: 7.5,  form: 7.3, nationality: 'Netherlands' },

  // ─── ALMERE CITY FC ─────────────────────────────────────────────────────────
  { name: 'Nordin Bakker',         display_name: 'Bakker',         position: 'GK',  club: 'Almere City', price: 4.5,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Cyril Ngonge',          display_name: 'Ngonge',         position: 'FWD', club: 'Almere City', price: 8.5,  form: 7.8, nationality: 'Belgium' },
  { name: 'Maarten Peijnenburg',   display_name: 'Peijnenburg',    position: 'MID', club: 'Almere City', price: 6.5,  form: 6.9, nationality: 'Netherlands' },
  { name: 'Arsenio Valpoort',      display_name: 'Valpoort',       position: 'MID', club: 'Almere City', price: 6.0,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Danilho Doekhi',        display_name: 'Doekhi',         position: 'DEF', club: 'Almere City', price: 5.5,  form: 6.6, nationality: 'Netherlands' },
  { name: 'Remy Heemskerk',        display_name: 'Heemskerk',      position: 'FWD', club: 'Almere City', price: 7.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Denso Kasius',          display_name: 'Kasius',         position: 'DEF', club: 'Almere City', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Jesse Bosch',           display_name: 'Bosch',          position: 'MID', club: 'Almere City', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Alex Plat',             display_name: 'Plat',           position: 'GK',  club: 'Almere City', price: 4.0,  form: 5.7, nationality: 'Netherlands' },
  { name: 'Mitchel Paulssen',      display_name: 'Paulssen',       position: 'DEF', club: 'Almere City', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Rajiv van la Parra',    display_name: 'Van la Parra',   position: 'FWD', club: 'Almere City', price: 7.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Oriol Busquets',        display_name: 'Busquets',       position: 'MID', club: 'Almere City', price: 6.5,  form: 6.9, nationality: 'Spain' },
  { name: 'Serhat Isma',           display_name: 'Isma',           position: 'FWD', club: 'Almere City', price: 7.5,  form: 7.4, nationality: 'Netherlands' },
  { name: 'Jeredy Hilterman',      display_name: 'Hilterman',      position: 'FWD', club: 'Almere City', price: 7.0,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Sylvester van der Water', display_name: 'Van der Water',position: 'FWD', club: 'Almere City', price: 7.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Gijs Smal ALM',         display_name: 'G.Smal',         position: 'DEF', club: 'Almere City', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Djevencio van der Kust ALM', display_name: 'Van der Kust',position: 'DEF', club: 'Almere City', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Javier Ybarra',         display_name: 'Ybarra',         position: 'MID', club: 'Almere City', price: 5.5,  form: 6.4, nationality: 'Spain' },
  { name: 'Theodor Bergstrom',     display_name: 'Bergstrom',      position: 'DEF', club: 'Almere City', price: 5.0,  form: 6.2, nationality: 'Sweden' },
  { name: 'Marko Vejinovic',       display_name: 'Vejinovic',      position: 'MID', club: 'Almere City', price: 6.0,  form: 6.6, nationality: 'Netherlands' },

  // ─── HERACLES ALMELO ────────────────────────────────────────────────────────
  { name: 'Michael Brouwer',       display_name: 'Brouwer',        position: 'GK',  club: 'Heracles Almelo', price: 4.5,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Bram Castro',           display_name: 'Castro',         position: 'GK',  club: 'Heracles Almelo', price: 4.0,  form: 5.8, nationality: 'Netherlands' },
  { name: 'Tim Breukers',          display_name: 'Breukers',       position: 'DEF', club: 'Heracles Almelo', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Ché Nunnely',           display_name: 'Nunnely',        position: 'FWD', club: 'Heracles Almelo', price: 7.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Jesse Bosch HER',       display_name: 'J.Bosch',        position: 'MID', club: 'Heracles Almelo', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Mike Eerdhuijzen',      display_name: 'Eerdhuijzen',    position: 'DEF', club: 'Heracles Almelo', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Feyerick Guzmán',       display_name: 'Guzmán',         position: 'FWD', club: 'Heracles Almelo', price: 7.0,  form: 7.1, nationality: 'Colombia' },
  { name: 'Thomas Bruns',          display_name: 'Bruns',          position: 'MID', club: 'Heracles Almelo', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Mark Diemers',          display_name: 'Diemers',        position: 'MID', club: 'Heracles Almelo', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Maarten Peijnenburg HER', display_name: 'Peijnenburg H', position: 'MID', club: 'Heracles Almelo', price: 6.0,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Raphael Brouwer',       display_name: 'R.Brouwer',      position: 'FWD', club: 'Heracles Almelo', price: 7.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Luciano Slagveer',      display_name: 'Slagveer',       position: 'FWD', club: 'Heracles Almelo', price: 7.5,  form: 7.4, nationality: 'Netherlands' },
  { name: 'Kevin Smit',            display_name: 'Smit',           position: 'FWD', club: 'Heracles Almelo', price: 7.0,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Nikolai Baden Frederiksen', display_name: 'Frederiksen', position: 'FWD', club: 'Heracles Almelo', price: 7.5,  form: 7.3, nationality: 'Denmark' },
  { name: 'Delano Ladan',          display_name: 'Ladan',          position: 'DEF', club: 'Heracles Almelo', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Saïd Bakari',           display_name: 'Bakari',         position: 'MID', club: 'Heracles Almelo', price: 5.5,  form: 6.5, nationality: 'Netherlands' },
  { name: 'Mario Engels',          display_name: 'Engels',         position: 'FWD', club: 'Heracles Almelo', price: 7.0,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Robin Gosens',          display_name: 'Gosens',         position: 'DEF', club: 'Heracles Almelo', price: 7.5,  form: 7.4, nationality: 'Germany' },
  { name: 'Anas Ouahim',           display_name: 'Ouahim',         position: 'MID', club: 'Heracles Almelo', price: 6.0,  form: 6.7, nationality: 'Morocco' },
  { name: 'Mikkel Kirkeskov',      display_name: 'Kirkeskov',      position: 'DEF', club: 'Heracles Almelo', price: 5.5,  form: 6.5, nationality: 'Denmark' },

  // ─── FORTUNA SITTARD ────────────────────────────────────────────────────────
  { name: 'Yanick van Osch',       display_name: 'Van Osch',       position: 'GK',  club: 'Fortuna Sittard', price: 4.5,  form: 6.1, nationality: 'Netherlands' },
  { name: 'Alexei Koselev',        display_name: 'Koselev',        position: 'GK',  club: 'Fortuna Sittard', price: 4.0,  form: 5.8, nationality: 'Kazakhstan' },
  { name: 'Zian Flemming',         display_name: 'Flemming',       position: 'MID', club: 'Fortuna Sittard', price: 8.0,  form: 7.7, nationality: 'Netherlands' },
  { name: 'Mark Diemers FOR',      display_name: 'Diemers F',      position: 'MID', club: 'Fortuna Sittard', price: 6.0,  form: 6.8, nationality: 'Netherlands' },
  { name: 'Derrick Köhn',          display_name: 'Köhn',           position: 'DEF', club: 'Fortuna Sittard', price: 5.5,  form: 6.6, nationality: 'Ghana' },
  { name: 'George Cox',            display_name: 'Cox',            position: 'DEF', club: 'Fortuna Sittard', price: 5.0,  form: 6.3, nationality: 'England' },
  { name: 'Stef Peeters FOR',      display_name: 'S.Peeters',      position: 'MID', club: 'Fortuna Sittard', price: 5.5,  form: 6.5, nationality: 'Belgium' },
  { name: 'Nick Russcher',         display_name: 'Russcher',       position: 'DEF', club: 'Fortuna Sittard', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Kwasi Wriedt',          display_name: 'Wriedt',         position: 'FWD', club: 'Fortuna Sittard', price: 8.0,  form: 7.6, nationality: 'Germany' },
  { name: 'Mats Seuntjens FOR',    display_name: 'M.Seuntjens',    position: 'FWD', club: 'Fortuna Sittard', price: 6.5,  form: 6.9, nationality: 'Netherlands' },
  { name: 'Jesper Drost',          display_name: 'Drost',          position: 'MID', club: 'Fortuna Sittard', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Nassim Bouaouzan',      display_name: 'Bouaouzan',      position: 'MID', club: 'Fortuna Sittard', price: 6.5,  form: 7.0, nationality: 'Morocco' },
  { name: 'Anass Najah',           display_name: 'Najah',          position: 'DEF', club: 'Fortuna Sittard', price: 5.0,  form: 6.3, nationality: 'Morocco' },
  { name: 'Bilal Ould-Chikh',      display_name: 'Ould-Chikh',     position: 'FWD', club: 'Fortuna Sittard', price: 7.5,  form: 7.4, nationality: 'Netherlands' },
  { name: 'Zian Flemming B',       display_name: 'Z.Flemming',     position: 'MID', club: 'Fortuna Sittard', price: 7.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Luca Pröpper',          display_name: 'L.Pröpper',      position: 'DEF', club: 'Fortuna Sittard', price: 5.0,  form: 6.2, nationality: 'Germany' },
  { name: 'Sven Köhler',           display_name: 'Köhler',         position: 'DEF', club: 'Fortuna Sittard', price: 5.0,  form: 6.3, nationality: 'Germany' },
  { name: 'Enzo Stroo',            display_name: 'Stroo',          position: 'FWD', club: 'Fortuna Sittard', price: 7.0,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Ryan Sanusi',           display_name: 'Sanusi',         position: 'MID', club: 'Fortuna Sittard', price: 6.0,  form: 6.6, nationality: 'Netherlands' },
  { name: 'Sander van de Streek FOR', display_name: 'Van de Streek F', position: 'MID', club: 'Fortuna Sittard', price: 6.0,  form: 6.6, nationality: 'Netherlands' },

  // ─── PEC ZWOLLE ─────────────────────────────────────────────────────────────
  { name: 'Xavier Mous',           display_name: 'Mous',           position: 'GK',  club: 'PEC Zwolle', price: 4.5,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Jasper Schendelaar PEC', display_name: 'Schendelaar P', position: 'GK',  club: 'PEC Zwolle', price: 4.0,  form: 5.8, nationality: 'Netherlands' },
  { name: 'Bram van Polen',        display_name: 'Van Polen',      position: 'DEF', club: 'PEC Zwolle', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Lennart Thy',           display_name: 'Thy',            position: 'FWD', club: 'PEC Zwolle', price: 8.0,  form: 7.5, nationality: 'Germany' },
  { name: 'Bram Nuytinck PEC',     display_name: 'B.Nuytinck',     position: 'DEF', club: 'PEC Zwolle', price: 5.0,  form: 6.2, nationality: 'Belgium' },
  { name: 'Gustavo Hamer',         display_name: 'Hamer',          position: 'MID', club: 'PEC Zwolle', price: 7.5,  form: 7.5, nationality: 'Brazil' },
  { name: 'Reza Ghoochannejhad',   display_name: 'Reza',           position: 'FWD', club: 'PEC Zwolle', price: 7.0,  form: 7.0, nationality: 'Iran' },
  { name: 'Reinou Geels',          display_name: 'Geels',          position: 'DEF', club: 'PEC Zwolle', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Yuta Nakayama',         display_name: 'Nakayama',       position: 'DEF', club: 'PEC Zwolle', price: 5.5,  form: 6.5, nationality: 'Japan' },
  { name: 'Teun Bijleveld',        display_name: 'Bijleveld',      position: 'MID', club: 'PEC Zwolle', price: 6.0,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Stef Peeters PEC',      display_name: 'St.Peeters',     position: 'MID', club: 'PEC Zwolle', price: 5.5,  form: 6.4, nationality: 'Belgium' },
  { name: 'Thomas Lam',            display_name: 'Lam',            position: 'DEF', club: 'PEC Zwolle', price: 5.0,  form: 6.2, nationality: 'Finland' },
  { name: 'Mike van Duinen',       display_name: 'Van Duinen',     position: 'FWD', club: 'PEC Zwolle', price: 7.0,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Yannick Tol',           display_name: 'Tol',            position: 'MID', club: 'PEC Zwolle', price: 6.0,  form: 6.6, nationality: 'Netherlands' },
  { name: 'Samuel Armenteros',     display_name: 'Armenteros',     position: 'FWD', club: 'PEC Zwolle', price: 7.0,  form: 7.0, nationality: 'Sweden' },
  { name: 'Daniël Crowl',          display_name: 'Crowl',          position: 'MID', club: 'PEC Zwolle', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Tim Lelieveld',         display_name: 'Lelieveld',      position: 'DEF', club: 'PEC Zwolle', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Ryan Thomas',           display_name: 'Thomas',         position: 'MID', club: 'PEC Zwolle', price: 7.0,  form: 7.2, nationality: 'New Zealand' },
  { name: 'Ricky van Haaren',      display_name: 'Van Haaren',     position: 'MID', club: 'PEC Zwolle', price: 6.5,  form: 6.9, nationality: 'Netherlands' },
  { name: 'Kenneth Paal',          display_name: 'Paal',           position: 'DEF', club: 'PEC Zwolle', price: 5.5,  form: 6.5, nationality: 'Netherlands' },

  // ─── FC VOLENDAM ────────────────────────────────────────────────────────────
  { name: 'Dani Böhm',             display_name: 'Böhm',           position: 'GK',  club: 'FC Volendam', price: 4.5,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Robert Mühren',         display_name: 'Mühren',         position: 'FWD', club: 'FC Volendam', price: 8.0,  form: 7.7, nationality: 'Netherlands' },
  { name: 'Derry John Murkin',     display_name: 'Murkin',         position: 'DEF', club: 'FC Volendam', price: 5.0,  form: 6.3, nationality: 'England' },
  { name: 'Martijn Fischer',       display_name: 'Fischer',        position: 'MID', club: 'FC Volendam', price: 6.0,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Henk Veerman VOL',      display_name: 'H.Veerman V',    position: 'FWD', club: 'FC Volendam', price: 7.5,  form: 7.3, nationality: 'Netherlands' },
  { name: 'Freek Heerkens',        display_name: 'Heerkens',       position: 'DEF', club: 'FC Volendam', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Jethro Mashart',        display_name: 'Mashart',        position: 'DEF', club: 'FC Volendam', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Henrico Drost',         display_name: 'H.Drost',        position: 'MID', club: 'FC Volendam', price: 6.0,  form: 6.6, nationality: 'Netherlands' },
  { name: 'Daan Tol',              display_name: 'D.Tol',          position: 'MID', club: 'FC Volendam', price: 6.0,  form: 6.7, nationality: 'Netherlands' },
  { name: 'Luca Plogmans',         display_name: 'Plogmans',       position: 'DEF', club: 'FC Volendam', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Carel Eiting',          display_name: 'Eiting',         position: 'MID', club: 'FC Volendam', price: 7.0,  form: 7.2, nationality: 'Netherlands' },
  { name: 'Kees Smit',             display_name: 'K.Smit',         position: 'FWD', club: 'FC Volendam', price: 7.0,  form: 7.1, nationality: 'Netherlands' },
  { name: 'Brian Plat',            display_name: 'B.Plat',         position: 'DEF', club: 'FC Volendam', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Xavier Mbuyamba',       display_name: 'Mbuyamba',       position: 'DEF', club: 'FC Volendam', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Danny Bakker',          display_name: 'D.Bakker',       position: 'MID', club: 'FC Volendam', price: 6.5,  form: 6.9, nationality: 'Netherlands' },
  { name: 'Billal Wahab',          display_name: 'Wahab',          position: 'FWD', club: 'FC Volendam', price: 7.5,  form: 7.3, nationality: 'Algeria' },
  { name: 'Anass Ahannach',        display_name: 'Ahannach',       position: 'MID', club: 'FC Volendam', price: 6.5,  form: 7.0, nationality: 'Morocco' },
  { name: 'Julian Baas VOL',       display_name: 'J.Baas V',       position: 'MID', club: 'FC Volendam', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Nani',                  display_name: 'Nani',           position: 'FWD', club: 'FC Volendam', price: 7.0,  form: 7.0, nationality: 'Portugal' },
  { name: 'Christos Donis',        display_name: 'Donis',          position: 'FWD', club: 'FC Volendam', price: 7.0,  form: 7.1, nationality: 'Greece' },

  // ─── EXCELSIOR ROTTERDAM ────────────────────────────────────────────────────
  { name: 'Alessandro Damen',      display_name: 'Damen',          position: 'GK',  club: 'Excelsior', price: 4.5,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Leeroy Owusu',          display_name: 'Owusu',          position: 'MID', club: 'Excelsior', price: 6.5,  form: 7.0, nationality: 'Netherlands' },
  { name: 'Kenzo Goudmijn',        display_name: 'Goudmijn',       position: 'MID', club: 'Excelsior', price: 7.5,  form: 7.5, nationality: 'Netherlands' },
  { name: 'Thijs Dallinga',        display_name: 'Dallinga',       position: 'FWD', club: 'Excelsior', price: 9.0,  form: 8.0, nationality: 'Netherlands' },
  { name: 'Matthew Agius',         display_name: 'Agius',          position: 'DEF', club: 'Excelsior', price: 5.0,  form: 6.3, nationality: 'Australia' },
  { name: 'Lazaros Rota',          display_name: 'Rota',           position: 'MID', club: 'Excelsior', price: 6.0,  form: 6.7, nationality: 'Greece' },
  { name: 'Haris Duljevic',        display_name: 'Duljevic',       position: 'MID', club: 'Excelsior', price: 6.5,  form: 6.9, nationality: 'Belgium' },
  { name: 'Elias Mar Ómarsson',    display_name: 'Ómarsson',       position: 'FWD', club: 'Excelsior', price: 7.5,  form: 7.4, nationality: 'Iceland' },
  { name: 'Rafael Steur',          display_name: 'Steur',          position: 'DEF', club: 'Excelsior', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Kevin Vermeulen',       display_name: 'Vermeulen',      position: 'DEF', club: 'Excelsior', price: 5.0,  form: 6.3, nationality: 'Netherlands' },
  { name: 'Siebe Schrijvers',      display_name: 'Schrijvers',     position: 'MID', club: 'Excelsior', price: 7.0,  form: 7.2, nationality: 'Belgium' },
  { name: 'Shurandy Sambo EXC',    display_name: 'S.Sambo',        position: 'DEF', club: 'Excelsior', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Magnus Mattsson',       display_name: 'Mattsson',       position: 'MID', club: 'Excelsior', price: 6.0,  form: 6.7, nationality: 'Sweden' },
  { name: 'Rik Vriend',            display_name: 'Vriend',         position: 'DEF', club: 'Excelsior', price: 5.0,  form: 6.2, nationality: 'Netherlands' },
  { name: 'Andreas Schellong',     display_name: 'Schellong',      position: 'MID', club: 'Excelsior', price: 6.0,  form: 6.6, nationality: 'Germany' },
  { name: 'Zeno Ibrahimovic',      display_name: 'Ibrahimovic',    position: 'FWD', club: 'Excelsior', price: 7.5,  form: 7.4, nationality: 'Bosnia' },
  { name: 'Daniel Arzani',         display_name: 'Arzani',         position: 'FWD', club: 'Excelsior', price: 7.0,  form: 7.1, nationality: 'Australia' },
  { name: 'Couhaib Driouech EXC',  display_name: 'C.Driouech',     position: 'FWD', club: 'Excelsior', price: 6.5,  form: 6.8, nationality: 'Morocco' },
  { name: 'Reuven Niemeijer EXC',  display_name: 'R.Niemeijer',    position: 'MID', club: 'Excelsior', price: 5.5,  form: 6.4, nationality: 'Netherlands' },
  { name: 'Gianluca Nijholt',      display_name: 'Nijholt',        position: 'GK',  club: 'Excelsior', price: 4.0,  form: 5.7, nationality: 'Netherlands' },
]
