export const MARKETPLACE_CONFIG = {
  FEE: 0.05, // 5%
  MIN_PRICE: 0.5,
  MAX_LISTING_HOURS: 168,
  MIN_BID_INCREMENT: 0.1,
}

export const FINANCIAL_CONFIG = {
  MIN_DEPOSIT: 5,
  MAX_DEPOSIT_DAILY: 500,
  MAX_DEPOSIT_WEEKLY: 2000,
  MIN_WITHDRAWAL: 10,
  EARLY_WITHDRAWAL_PENALTY: 0.10,
  WITHDRAWAL_PROCESSING_DAYS: 3,
}

export const SEASON_CONFIG = {
  PLATFORM_FEE_PCT: 0.20, // 20%
  TEAM_BUDGET: 100,
  MAX_PLAYERS_FROM_CLUB: 3,
  TEAM_SIZE: 15,
  FREE_TRANSFERS_PER_WEEK: 1,
}
