import { Player, Match, LeaderboardEntry, MarketplaceListing, Transaction, Powerup, User, Notification, Team, TeamPlayer, MatchEvent, PricePoint } from '@/types'

// ─── Mock Users ───────────────────────────────────────────────────────────────

export const mockCurrentUser: User = {
  id: 'user_001',
  email: 'jan@example.nl',
  username: 'JanDeVoetbalfan',
  balance_credits: 47.50,
  tier: 'gold',
  kyc_status: 'verified',
  role: 'user',
  avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jan',
  created_at: '2024-01-15T10:00:00Z',
  last_login: '2024-06-15T08:30:00Z',
  seasons_played: 4,
  best_finish: 12,
  total_winnings: 234.50,
  total_invested: 680.00,
  is_suspended: false,
}

// ─── Mock Players ─────────────────────────────────────────────────────────────

export const mockPlayers: Player[] = [
  {
    id: 'p1',
    name: 'E. Haaland',
    first_name: 'Erling',
    last_name: 'Haaland',
    club: 'Manchester City',
    club_id: 'mci',
    nationality: 'Noors',
    position: 'FWD',
    price: 14.5,
    form: 9.2,
    availability: 'available',
    photo_url: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p223094.png',
    total_points: 287,
    points_this_week: 18,
    goals: 24,
    assists: 5,
    clean_sheets: 0,
    yellow_cards: 2,
    red_cards: 0,
    fixture_difficulty: 2,
    upcoming_fixtures: [
      { opponent: 'Arsenal', home_away: 'H', date: '2024-06-22', difficulty: 3 },
      { opponent: 'Wolves', home_away: 'A', date: '2024-06-29', difficulty: 1 },
    ],
    form_history: [12, 8, 18, 6, 15, 18],
    owned_by_percent: 67.3,
    price_change_week: 0.3,
  },
  {
    id: 'p2',
    name: 'M. Salah',
    first_name: 'Mohamed',
    last_name: 'Salah',
    club: 'Liverpool',
    club_id: 'liv',
    nationality: 'Egyptisch',
    position: 'FWD',
    price: 13.0,
    form: 8.8,
    availability: 'available',
    photo_url: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p118748.png',
    total_points: 241,
    points_this_week: 12,
    goals: 19,
    assists: 12,
    clean_sheets: 0,
    yellow_cards: 1,
    red_cards: 0,
    fixture_difficulty: 3,
    upcoming_fixtures: [
      { opponent: 'Chelsea', home_away: 'H', date: '2024-06-22', difficulty: 3 },
      { opponent: 'Crystal Palace', home_away: 'A', date: '2024-06-29', difficulty: 2 },
    ],
    form_history: [9, 12, 6, 15, 12, 12],
    owned_by_percent: 58.1,
    price_change_week: 0.1,
  },
  {
    id: 'p3',
    name: 'B. Saka',
    first_name: 'Bukayo',
    last_name: 'Saka',
    club: 'Arsenal',
    club_id: 'ars',
    nationality: 'Engels',
    position: 'MID',
    price: 10.5,
    form: 8.5,
    availability: 'available',
    photo_url: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p223340.png',
    total_points: 198,
    points_this_week: 10,
    goals: 16,
    assists: 9,
    clean_sheets: 2,
    yellow_cards: 3,
    red_cards: 0,
    fixture_difficulty: 2,
    upcoming_fixtures: [
      { opponent: 'Man City', home_away: 'A', date: '2024-06-22', difficulty: 4 },
      { opponent: 'Brighton', home_away: 'H', date: '2024-06-29', difficulty: 2 },
    ],
    form_history: [8, 10, 12, 6, 9, 10],
    owned_by_percent: 42.7,
    price_change_week: 0.2,
  },
  {
    id: 'p4',
    name: 'T. Alexander-Arnold',
    first_name: 'Trent',
    last_name: 'Alexander-Arnold',
    club: 'Liverpool',
    club_id: 'liv',
    nationality: 'Engels',
    position: 'DEF',
    price: 9.5,
    form: 7.8,
    availability: 'available',
    photo_url: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p184341.png',
    total_points: 169,
    points_this_week: 8,
    goals: 3,
    assists: 14,
    clean_sheets: 9,
    yellow_cards: 2,
    red_cards: 0,
    fixture_difficulty: 3,
    upcoming_fixtures: [
      { opponent: 'Chelsea', home_away: 'H', date: '2024-06-22', difficulty: 3 },
      { opponent: 'Crystal Palace', home_away: 'A', date: '2024-06-29', difficulty: 2 },
    ],
    form_history: [6, 8, 10, 8, 9, 8],
    owned_by_percent: 39.4,
    price_change_week: -0.1,
  },
  {
    id: 'p5',
    name: 'A. Raya',
    first_name: 'David',
    last_name: 'Raya',
    club: 'Arsenal',
    club_id: 'ars',
    nationality: 'Spaans',
    position: 'GK',
    price: 6.0,
    form: 7.2,
    availability: 'available',
    photo_url: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p117315.png',
    total_points: 145,
    points_this_week: 6,
    goals: 0,
    assists: 0,
    clean_sheets: 12,
    yellow_cards: 1,
    red_cards: 0,
    saves: 87,
    fixture_difficulty: 2,
    upcoming_fixtures: [
      { opponent: 'Man City', home_away: 'A', date: '2024-06-22', difficulty: 4 },
      { opponent: 'Brighton', home_away: 'H', date: '2024-06-29', difficulty: 2 },
    ],
    form_history: [6, 8, 6, 10, 8, 6],
    owned_by_percent: 28.9,
    price_change_week: 0.0,
  },
  {
    id: 'p6',
    name: 'O. Watkins',
    first_name: 'Ollie',
    last_name: 'Watkins',
    club: 'Aston Villa',
    club_id: 'avl',
    nationality: 'Engels',
    position: 'FWD',
    price: 8.5,
    form: 8.1,
    availability: 'available',
    total_points: 187,
    points_this_week: 9,
    goals: 19,
    assists: 13,
    clean_sheets: 0,
    yellow_cards: 2,
    red_cards: 0,
    fixture_difficulty: 3,
    upcoming_fixtures: [
      { opponent: 'Tottenham', home_away: 'H', date: '2024-06-22', difficulty: 3 },
    ],
    form_history: [9, 10, 6, 12, 8, 9],
    owned_by_percent: 35.6,
    price_change_week: 0.1,
  },
  {
    id: 'p7',
    name: 'P. Foden',
    first_name: 'Phil',
    last_name: 'Foden',
    club: 'Manchester City',
    club_id: 'mci',
    nationality: 'Engels',
    position: 'MID',
    price: 11.0,
    form: 8.6,
    availability: 'available',
    total_points: 212,
    points_this_week: 11,
    goals: 19,
    assists: 8,
    clean_sheets: 5,
    yellow_cards: 1,
    red_cards: 0,
    fixture_difficulty: 2,
    upcoming_fixtures: [
      { opponent: 'Arsenal', home_away: 'H', date: '2024-06-22', difficulty: 3 },
    ],
    form_history: [11, 8, 14, 9, 12, 11],
    owned_by_percent: 45.2,
    price_change_week: 0.2,
  },
  {
    id: 'p8',
    name: 'V. van Dijk',
    first_name: 'Virgil',
    last_name: 'van Dijk',
    club: 'Liverpool',
    club_id: 'liv',
    nationality: 'Nederlands',
    position: 'DEF',
    price: 6.5,
    form: 6.8,
    availability: 'available',
    total_points: 142,
    points_this_week: 6,
    goals: 4,
    assists: 1,
    clean_sheets: 10,
    yellow_cards: 3,
    red_cards: 0,
    fixture_difficulty: 3,
    upcoming_fixtures: [
      { opponent: 'Chelsea', home_away: 'H', date: '2024-06-22', difficulty: 3 },
    ],
    form_history: [6, 6, 8, 6, 6, 6],
    owned_by_percent: 22.1,
    price_change_week: 0.0,
  },
  {
    id: 'p9',
    name: 'C. Palmer',
    first_name: 'Cole',
    last_name: 'Palmer',
    club: 'Chelsea',
    club_id: 'che',
    nationality: 'Engels',
    position: 'MID',
    price: 10.0,
    form: 9.0,
    availability: 'available',
    total_points: 244,
    points_this_week: 14,
    goals: 22,
    assists: 11,
    clean_sheets: 3,
    yellow_cards: 2,
    red_cards: 0,
    fixture_difficulty: 2,
    upcoming_fixtures: [
      { opponent: 'Liverpool', home_away: 'A', date: '2024-06-22', difficulty: 4 },
    ],
    form_history: [14, 16, 12, 18, 14, 14],
    owned_by_percent: 52.8,
    price_change_week: 0.4,
  },
  {
    id: 'p10',
    name: 'J. Pedro',
    first_name: 'João',
    last_name: 'Pedro',
    club: 'Brighton',
    club_id: 'bha',
    nationality: 'Braziliaans',
    position: 'FWD',
    price: 6.0,
    form: 7.0,
    availability: 'doubt',
    total_points: 112,
    points_this_week: 4,
    goals: 12,
    assists: 5,
    clean_sheets: 0,
    yellow_cards: 2,
    red_cards: 0,
    fixture_difficulty: 4,
    upcoming_fixtures: [
      { opponent: 'Arsenal', home_away: 'A', date: '2024-06-29', difficulty: 4 },
    ],
    form_history: [4, 6, 8, 4, 6, 4],
    owned_by_percent: 18.3,
    price_change_week: -0.2,
  },
  {
    id: 'p11',
    name: 'A. Mykolenko',
    first_name: 'Vitaly',
    last_name: 'Mykolenko',
    club: 'Everton',
    club_id: 'eve',
    nationality: 'Oekraïens',
    position: 'DEF',
    price: 4.5,
    form: 5.5,
    availability: 'available',
    total_points: 89,
    points_this_week: 2,
    goals: 1,
    assists: 2,
    clean_sheets: 6,
    yellow_cards: 4,
    red_cards: 0,
    fixture_difficulty: 2,
    upcoming_fixtures: [
      { opponent: 'Luton', home_away: 'H', date: '2024-06-22', difficulty: 1 },
    ],
    form_history: [2, 4, 2, 6, 2, 2],
    owned_by_percent: 8.7,
    price_change_week: 0.0,
  },
]

// ─── Mock Matches ─────────────────────────────────────────────────────────────

export const mockMatches: Match[] = [
  {
    id: 'match_001',
    home_team: 'Manchester City',
    away_team: 'Arsenal',
    home_team_id: 'mci',
    away_team_id: 'ars',
    status: 'live',
    minute: 67,
    home_score: 2,
    away_score: 1,
    events: [
      { id: 'e1', type: 'goal', player_id: 'p1', player_name: 'E. Haaland', team: 'Manchester City', minute: 23, points_awarded: 6, is_my_player: true },
      { id: 'e2', type: 'assist', player_id: 'p7', player_name: 'P. Foden', team: 'Manchester City', minute: 23, points_awarded: 3, is_my_player: true },
      { id: 'e3', type: 'goal', player_id: 'p3', player_name: 'B. Saka', team: 'Arsenal', minute: 51, points_awarded: 5, is_my_player: false },
      { id: 'e4', type: 'goal', player_id: 'p1', player_name: 'E. Haaland', team: 'Manchester City', minute: 64, points_awarded: 6, is_my_player: true },
    ],
    gameweek: 38,
    kickoff_time: '2024-06-22T15:00:00Z',
    venue: 'Etihad Stadium',
    my_players_in_match: ['p1', 'p7'],
    my_points_from_match: 17,
  },
  {
    id: 'match_002',
    home_team: 'Liverpool',
    away_team: 'Chelsea',
    home_team_id: 'liv',
    away_team_id: 'che',
    status: 'live',
    minute: 34,
    home_score: 1,
    away_score: 1,
    events: [
      { id: 'e5', type: 'goal', player_id: 'p2', player_name: 'M. Salah', team: 'Liverpool', minute: 12, points_awarded: 6, is_my_player: true },
      { id: 'e6', type: 'goal', player_id: 'p9', player_name: 'C. Palmer', team: 'Chelsea', minute: 29, points_awarded: 5, is_my_player: false },
    ],
    gameweek: 38,
    kickoff_time: '2024-06-22T15:00:00Z',
    venue: 'Anfield',
    my_players_in_match: ['p2', 'p4', 'p8'],
    my_points_from_match: 8,
  },
  {
    id: 'match_003',
    home_team: 'Aston Villa',
    away_team: 'Tottenham',
    home_team_id: 'avl',
    away_team_id: 'tot',
    status: 'scheduled',
    minute: 0,
    home_score: 0,
    away_score: 0,
    events: [],
    gameweek: 38,
    kickoff_time: '2024-06-22T17:30:00Z',
    venue: 'Villa Park',
    my_players_in_match: ['p6'],
    my_points_from_match: 0,
  },
]

// ─── Mock Leaderboard ─────────────────────────────────────────────────────────

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, previous_rank: 2, user: { id: 'u1', username: 'FootballKing2024', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=King', tier: 'rare' }, team_name: 'Dream Team FC', total_points: 1842, gameweek_points: 94, prize: 2400 },
  { rank: 2, previous_rank: 1, user: { id: 'u2', username: 'VoetbalMaster', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Master', tier: 'platinum' }, team_name: 'Ajax Fans XI', total_points: 1798, gameweek_points: 88, prize: 1200 },
  { rank: 3, previous_rank: 3, user: { id: 'u3', username: 'TacticalGenius', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Genius', tier: 'platinum' }, team_name: 'Tactical Titans', total_points: 1756, gameweek_points: 76, prize: 800 },
  { rank: 4, previous_rank: 6, user: { id: 'u4', username: 'GoalMachine', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Goal', tier: 'gold' }, team_name: 'Goal Machine FC', total_points: 1734, gameweek_points: 82, prize: 400 },
  { rank: 5, previous_rank: 4, user: { id: 'u5', username: 'NederVoetbal', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Neder', tier: 'gold' }, team_name: 'Oranje Power', total_points: 1698, gameweek_points: 71, prize: 300 },
  { rank: 12, previous_rank: 14, user: { id: 'user_001', username: 'JanDeVoetbalfan', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jan', tier: 'gold' }, team_name: 'Jan\'s Legends', total_points: 1456, gameweek_points: 65, prize: 120, is_current_user: true },
  { rank: 13, previous_rank: 11, user: { id: 'u7', username: 'PietjeVoetbal', avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pietje', tier: 'silver' }, team_name: 'Pietje\'s Dream', total_points: 1434, gameweek_points: 58, prize: 100 },
]

// ─── Mock Marketplace Listings ─────────────────────────────────────────────────

export const mockListings: MarketplaceListing[] = [
  {
    id: 'l1',
    player: mockPlayers[0],
    seller_id: 'u3',
    seller_username: 'TacticalGenius',
    price: 16.5,
    bid_count: 8,
    current_bid: 16.5,
    listing_type: 'auction',
    status: 'active',
    expires_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    transaction_fee: 0.825,
    price_history: [
      { date: '2024-06-15', price: 14.0 },
      { date: '2024-06-16', price: 14.3 },
      { date: '2024-06-17', price: 14.5 },
      { date: '2024-06-18', price: 14.8 },
      { date: '2024-06-19', price: 15.2 },
      { date: '2024-06-20', price: 15.8 },
      { date: '2024-06-21', price: 16.5 },
    ],
  },
  {
    id: 'l2',
    player: mockPlayers[2],
    seller_id: 'u5',
    seller_username: 'NederVoetbal',
    price: 11.0,
    bid_count: 0,
    listing_type: 'fixed',
    status: 'active',
    expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    transaction_fee: 0.55,
    price_history: [
      { date: '2024-06-15', price: 10.0 },
      { date: '2024-06-18', price: 10.5 },
      { date: '2024-06-21', price: 11.0 },
    ],
  },
  {
    id: 'l3',
    player: mockPlayers[8],
    seller_id: 'u4',
    seller_username: 'GoalMachine',
    price: 10.5,
    bid_count: 5,
    current_bid: 10.5,
    listing_type: 'auction',
    status: 'active',
    expires_at: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    transaction_fee: 0.525,
    price_history: [
      { date: '2024-06-14', price: 9.5 },
      { date: '2024-06-17', price: 10.0 },
      { date: '2024-06-21', price: 10.5 },
    ],
  },
]

// ─── Mock Transactions ─────────────────────────────────────────────────────────

export const mockTransactions: Transaction[] = [
  { id: 't1', user_id: 'user_001', type: 'deposit', amount: 1100, balance_after: 5000, created_at: '2024-06-10T14:00:00Z', reference: 'DEP-001-2024', description: 'Pro pakket — 1100 coins', status: 'completed' },
  { id: 't2', user_id: 'user_001', type: 'marketplace_purchase', amount: -200, balance_after: 4800, created_at: '2024-06-10T14:05:00Z', reference: 'MKT-BUY-002', description: 'Aankoop L. Diaz', status: 'completed' },
  { id: 't3', user_id: 'user_001', type: 'marketplace_purchase', amount: -165, balance_after: 4635, created_at: '2024-06-12T10:30:00Z', reference: 'MKT-BUY-001', description: 'Aankoop E. Haaland', status: 'completed' },
  { id: 't4', user_id: 'user_001', type: 'marketplace_sale', amount: 124, balance_after: 4759, created_at: '2024-06-14T16:00:00Z', reference: 'MKT-SELL-001', description: 'Verkoop M. Rashford', status: 'completed' },
  { id: 't5', user_id: 'user_001', type: 'powerup_purchase', amount: -50, balance_after: 4709, created_at: '2024-06-15T09:00:00Z', reference: 'PWR-001', description: 'Dubbele Punten power-up', status: 'completed' },
  { id: 't6', user_id: 'user_001', type: 'coin_reward', amount: 200, balance_after: 4909, created_at: '2024-06-18T12:00:00Z', reference: 'REWARD-GW37-012', description: 'Coin beloning GW37 - Rank #12', status: 'completed' },
]

// ─── Mock Power-ups ───────────────────────────────────────────────────────────

export const mockPowerups: Powerup[] = [
  {
    id: 'pw1',
    type: 'double_points',
    name: 'Dubbele Punten',
    description: 'Verdubbelt alle punten voor één speelronde',
    cost: 5,
    status: 'available',
    active: false,
  },
  {
    id: 'pw2',
    type: 'negative_shield',
    name: 'Negatief Schild',
    description: 'Voorkomt negatieve punten voor één wedstrijd',
    cost: 3,
    status: 'active',
    active: true,
    expires_at: '2024-06-22T22:00:00Z',
    applied_gameweek: 38,
    purchased_at: '2024-06-20T10:00:00Z',
  },
  {
    id: 'pw3',
    type: 'hot_transfer',
    name: 'Hot Transfer',
    description: 'Gratis transfer buiten het transferwindow',
    cost: 2,
    status: 'available',
    active: false,
  },
]

// ─── Mock Notifications ───────────────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  { id: 'n1', type: 'match_event', title: 'Haaland scoort!', message: 'E. Haaland heeft gescoord in Man City vs Arsenal (+6 punten)', read: false, created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
  { id: 'n2', type: 'prize', title: 'Prijs ontvangen!', message: 'Je hebt €120 gewonnen voor rank #12 in GW37', read: false, created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
  { id: 'n3', type: 'trade', title: 'Bod ontvangen', message: 'Nieuw bod van 16.5 credits op jouw Haaland listing', read: true, created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString() },
  { id: 'n4', type: 'transfer_window', title: 'Transferwindow geopend', message: 'Het transferwindow is open tot vrijdag 18:00', read: true, created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString() },
  { id: 'n5', type: 'system', title: 'Seizoen 38 begint!', message: 'Stel je team in voor het nieuwe seizoen. Deadline: vrijdag 18:00', read: true, created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
]

// ─── Mock Team ────────────────────────────────────────────────────────────────

export const mockTeam: Team = {
  id: 'team_001',
  user_id: 'user_001',
  season_id: 's1',
  name: 'Jan\'s Dream Team',
  formation: '4-3-3',
  players: [
    { player_id: 'p5', position: 'GK', is_captain: false, is_vice_captain: false, purchase_price: 5.0, slot: 1, is_benched: false },
    { player_id: 'p4', position: 'DEF', is_captain: false, is_vice_captain: false, purchase_price: 9.5, slot: 2, is_benched: false },
    { player_id: 'p6', position: 'DEF', is_captain: false, is_vice_captain: false, purchase_price: 7.0, slot: 3, is_benched: false },
    { player_id: 'p7', position: 'DEF', is_captain: false, is_vice_captain: false, purchase_price: 6.5, slot: 4, is_benched: false },
    { player_id: 'p8', position: 'DEF', is_captain: false, is_vice_captain: false, purchase_price: 6.0, slot: 5, is_benched: false },
    { player_id: 'p3', position: 'MID', is_captain: false, is_vice_captain: true, purchase_price: 10.5, slot: 6, is_benched: false },
    { player_id: 'p9', position: 'MID', is_captain: false, is_vice_captain: false, purchase_price: 8.5, slot: 7, is_benched: false },
    { player_id: 'p10', position: 'MID', is_captain: false, is_vice_captain: false, purchase_price: 7.5, slot: 8, is_benched: false },
    { player_id: 'p2', position: 'FWD', is_captain: false, is_vice_captain: false, purchase_price: 13.0, slot: 9, is_benched: false },
    { player_id: 'p11', position: 'FWD', is_captain: false, is_vice_captain: false, purchase_price: 8.0, slot: 10, is_benched: false },
    { player_id: 'p1', position: 'FWD', is_captain: true, is_vice_captain: false, purchase_price: 14.5, slot: 11, is_benched: false },
  ],
  captain_id: 'p1',
  vice_captain_id: 'p3',
  total_points: 1284,
  gameweek_points: 47,
  budget_remaining: 4.0,
  budget_total: 100,
  transfers_remaining: 1,
  created_at: '2024-08-01T10:00:00Z',
  updated_at: '2024-06-15T10:00:00Z',
}

// ─── Mock Match Events ────────────────────────────────────────────────────────

export const mockMatchEvents: Record<string, MatchEvent[]> = {
  'm1': [
    { id: 'e1', type: 'goal', player_id: 'p1', player_name: 'E. Haaland', team: 'Manchester City', minute: 23, points_awarded: 6, is_my_player: true },
    { id: 'e2', type: 'assist', player_id: 'p3', player_name: 'B. Saka', team: 'Arsenal', minute: 31, points_awarded: 3, is_my_player: true },
    { id: 'e3', type: 'yellow_card', player_id: 'ext1', player_name: 'T. Partey', team: 'Arsenal', minute: 45, points_awarded: -1, is_my_player: false },
    { id: 'e4', type: 'goal', player_id: 'p1', player_name: 'E. Haaland', team: 'Manchester City', minute: 67, points_awarded: 6, is_my_player: true },
    { id: 'e5', type: 'goal', player_id: 'ext2', player_name: 'M. Ødegaard', team: 'Arsenal', minute: 78, points_awarded: 8, is_my_player: false },
  ],
  'm2': [
    { id: 'e6', type: 'goal', player_id: 'p2', player_name: 'M. Salah', team: 'Liverpool', minute: 12, points_awarded: 6, is_my_player: true },
    { id: 'e7', type: 'clean_sheet', player_id: 'p4', player_name: 'T. Alexander-Arnold', team: 'Liverpool', minute: 90, points_awarded: 4, is_my_player: true },
  ],
}

// ─── Mock Price History ───────────────────────────────────────────────────────

export const mockPriceHistory: PricePoint[] = Array.from({ length: 14 }, (_, i) => ({
  date: new Date(Date.now() - (13 - i) * 24 * 60 * 60 * 1000).toISOString(),
  price: 13.5 + Math.sin(i * 0.5) * 0.8 + i * 0.05,
}))

// ─── Mock User Powerups ───────────────────────────────────────────────────────

export const mockUserPowerups = mockPowerups
